# Generated by Django 5.1.4 on 2024-12-22 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionText', models.CharField(max_length=120)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveysApp.questions')),
            ],
        ),
        migrations.CreateModel(
            name='OpenAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveysApp.questions')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveysApp.questions')),
            ],
        ),
    ]
